repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe
      - id: check-xml
        files: \.csproj$
        types: [file]
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent=4"]
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.43.0
    hooks:
      - id: cfn-python-lint
        files: template.*\.yaml$