repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
        exclude: \.vscode
      - id: pretty-format-json
        args:
          - --autofix
      - id: check-xml
        files: \.csproj$
        types: [file]
      - id: check-yaml
        args:
          - --unsafe
      - id: mixed-line-ending
        args:
          - --fix=crlf
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.59.1
    hooks:
      - id: cfn-python-lint
        files: template.*\.yaml$
