AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Event Sauce API

Parameters:
  PolicyStackName:
    Type: String
    Default: event-sauce-api-iam
    Description: The name of the stack that declares this stacks IAM policy ARNs

Resources:
  EventSauceApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: publish/EventSauceApi
      Handler: EventSauceApi::EventSauceApi.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      MemorySize: 256
      Timeout: 20
      Role:
        Fn::ImportValue:
          !Sub "${PolicyStackName}-EventSauceApiFunctionRoleArn"
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: ""
      Events:
        Proxy:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
            RestApiId: !Ref EventSauceApi
        Root:
          Type: Api
          Properties:
            Path: "/"
            Method: "ANY"
            RestApiId: !Ref EventSauceApi

  EventSauceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: event-sauce-api
      StageName: Prod

Outputs:
  EventSauceApiDomainName:
    Description: "API Gateway domain name"
    Value: !Sub "${EventSauceApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: "event-sauce-api-DomainName"