AWSTemplateFormatVersion: "2010-09-09"
Description: Event Sauce API IAM

Parameters:
  EventSauceApiStackName:
    Type: String
    Default: event-sauce-api
    Description: The name of the stack using the roles within this stack

Resources:
  CloudFormation:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: CloudFormation
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: cloudformation:*
            Resource:
              - !Sub arn:aws:cloudformation:*:*:stack/${EventSauceApiStackName}/*
              - arn:aws:cloudformation:eu-west-1:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub arn:aws:iam::*:role/${AWS::StackName}-*
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:GetRole
              - iam:PassRole
            Resource:
              - !Sub arn:aws:iam::*:role/${EventSauceApiStackName}-*
          - Effect: Allow
            Action:
              - lambda:*
            Resource:
              - !Sub arn:*:lambda:*:*:function:${EventSauceApiStackName}-*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:DeleteLogGroup
              - logs:DeleteRetentionPolicy
              - logs:DescribeLogGroups
              - logs:PutRetentionPolicy
            Resource:
              - !Sub arn:*:logs:*:*:log-group:/aws/lambda/${EventSauceApiStackName}-*
          - Effect: Allow
            Action:
              - apigateway:*
            Resource:
              - arn:aws:execute-api:*
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service:
            - cloudformation.amazonaws.com

  EventSauceApiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
      - PolicyName: EventSauceApiFunctionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - cloudwatch:PutMetricData
            Resource:
              - !Sub arn:aws:cloudwatch:*:*:stream/${EventSauceApiStackName}-*
            Effect: Allow
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com

Outputs:
  EventSauceApiFunctionRoleArn:
    Value: !GetAtt EventSauceApiFunctionRole.Arn
    Description: The EventSauceApiFunctionRole Arn
    Export:
      Name: !Sub "${AWS::StackName}-EventSauceApiFunctionRoleArn"
