version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  test-and-package:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - checkout
      - run:
          name: Test and Package
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install -g Cake.Tool
            dotnet cake --target=Package
      - persist_to_workspace:
            root: .
            paths:
              - template.yaml
              - publish

  e2e-test:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install apt-transport-https
            sudo apt-get install dotnet-sdk-3.1
            sudo apt-get install python-is-python3
            pip install --upgrade pip
            pip install --user awscli
            pip install --user aws-sam-cli
            dotnet tool install --tool-path . Cake.Tool
            dotnet tool install --tool-path . trx2junit
            chmod 755 dotnet-cake
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
      - run:
          name: Run E2E Tests
          command: |
            ./dotnet-cake --target=Test-E2E
      - run:
          name: Export Test Results
          command: ./trx2junit ./artifacts/*.trx
          when: always
      - store_test_results:
          path: ./artifacts/

  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .q
      - aws-cli/setup:
          version: '2'
      - run:
          name: Create Change Set
          command: |
            CHANGESET_NAME=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            S3_PREFIX=event-sauce-api/$CHANGESET_NAME
            aws cloudformation package --template-file template.yaml \
              --s3-bucket $CF_DEPLOYMENT_S3_BUCKET \
              --s3-prefix $S3_PREFIX \
              --output-template-file template-processed.yaml
            aws s3 cp template-processed.yaml s3://$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/
            aws cloudformation create-change-set \
              --template-url https://s3-eu-west-1.amazonaws.com/$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/template-processed.yaml \
              --stack-name event-sauce \
              --change-set-name $CHANGESET_NAME \
              --description "Created by CircleCI $CIRCLE_BUILD_URL"

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test-and-package
      - e2e-test:
          name: e2e-test
          requires:
            - test-and-package
      - deploy:
          name: aws-deploy
          context: aws-deployment
          requires:
            - e2e-test
          filters:
            branches:
              only: master
