version: "3.4"
services:
  localstack:
    image: localstack/localstack:0.12.2
    ports:
      - "3020:8080"
      - "4566:4566" # LocalStack services
    environment:
      - SERVICES=${SERVICES-dynamodb}
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
    restart: unless-stopped