version: 2.1
jobs:
  test-and-package:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2.204
    steps:
      - checkout
      - run:
          name: Test and package
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install -g Cake.Tool
            dotnet cake --target=Package
      - persist_to_workspace:
            root: .
            paths:
              - template.yaml
              - openapi
              - publish
  e2e-test:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get install apt-transport-https
            sudo apt-get update
            sudo apt-get install dotnet-sdk-2.2=2.2.204-1
            pyenv global 3.7.0
            pip install --upgrade pip
            pip install --user awscli
            pip install --user aws-sam-cli==0.37.0
            dotnet tool install --tool-path . Cake.Tool
            dotnet tool install --tool-path . trx2junit
            chmod 755 dotnet-cake
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
      - run:
          name: E2E Tests
          command: |
            ./dotnet-cake --target=Test-E2E
      - run:
          name: Export Test Results
          command: ./trx2junit ./artifacts/*.trx
          when: always
      - store_test_results:
          path: ./artifacts/

  deploy:
    docker:
     - image: circleci/python:3-node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Create change set
          command: |
            CHANGESET_NAME=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            S3_PREFIX=event-sauce-api/$CHANGESET_NAME
            aws cloudformation package --template-file template.yaml \
              --s3-bucket $CF_DEPLOYMENT_S3_BUCKET \
              --s3-prefix $S3_PREFIX \
              --output-template-file template-processed.yaml
            aws s3 cp template-processed.yaml s3://$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/
            aws cloudformation create-change-set \
              --template-url https://s3-eu-west-1.amazonaws.com/$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/template-processed.yaml \
              --stack-name event-sauce \
              --change-set-name $CHANGESET_NAME \
              --description "Build: $CIRCLE_BUILD_URL" \
              --capabilities CAPABILITY_IAM

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test-and-package
      - e2e-test
      - deploy:
          name: deploy
          is_prod: true
          context: aws-cf-deployment-prod
          requires:
            - test-and-package
            - e2e-test
          filters:
            branches:
              only: master